export const INIT_DATA = "INIT_DATA";
export const SELECT_PLAN = "SELECT_PLAN";
export const MILES_TO_BE_DRIVEN = "MILES_TO_BE_DRIVEN";
export const RATE_SELECT = "RATE_SELECT";

export const CALCULATE_RESULT = "CALCULATE_RESULT";
export const DISPLAY_RESULT = "DISPLAY_RESULT";
